name: build
on: [push, workflow_dispatch]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read
  
jobs:
  build_with_self_hosted:
    runs-on: my-permanent-runner
    name: Build with self-hosted runner
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4

  build_with_docker:
    runs-on: ubuntu-latest
    name: Build with Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4

  build_with_nscloud:
    runs-on: ubuntu-latest
    name: Build with Namespace Cloud push to local registry
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure access to Namespace
        id: nscloud
        uses: namespacelabs/nscloud-setup@v0
      - name: Configure Docker to use Namespace Remote Builders
        uses: namespacelabs/nscloud-setup-buildx-action@v0 
      - name: Build and push
        uses: docker/build-push-action@v4
